version: '3'

services:
  node:
    environment:
      - PORT=3000
    image: node:latest
    volumes: 
     - ./:/code
    working_dir: /code
    ports:
      - 5000:3000
    command: 'sleep infinity'